### PR TITLE
PostgreSQL support

### PR DESCRIPTION
**Pull request by avaly**
:alien:

### CODE REVIEW

**Comment by ahawkins** [comment]
@avaly ZOMG. You have no idea how happy this makes me. Is there a way to test without a DB, username, and password? We ran into this issue with MySQL where the application creates the DB, so there is nothing to connect to yet.

**Comment by avaly** [comment]
I guess this last change could work: using the default `postgres` user and connect to the `postgres` db.

Don't forget to autosquash the commits if you want to merge it.

**Review by vutny — COMMENTED** [review]
Such an old PR, even got conflicts...

What would be super awesome is to be able to provide a query like `SELECT * FROM table;` and check if it returns any result.
Seems `pg8000` library supports that in easy way.

I hope you @avaly will find some time to push this PR to be finally accepted.

**Comment by avaly** [comment]
Sorry, but I'm not using this project any more. I won't have time for updates. Feel free to reuse the code.

**Comment by vutny** [comment]
Thanks for your work anyway!

**Pull request closed without merging**
